name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona la repo
    - uses: actions/checkout@v3

    # 2. Imposta Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Installa dipendenze direttamente
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy tabulate mpmath pytest qutip copy


    # 4. Esegui i test
    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest

